### ISSUE TITLE
Will there be Gfycat support?

### ISSUE THREAD

**Issue by ChippSkylark** [makuto/Liked-Saved-Image-Downloader#16]

**Comment by ChippSkylark** [comment]
Oh, I must have done something wrong then. My script refused to download any reddit post related to gfycat. It also randomly skipped some images, but that's a separate matter I gotta look at.

**Comment by makuto** [comment]
If you can send me the URLs of the reddit posts and gfycat URLs which do not work I can try them myself and see what I can find.

**Comment by makuto** [comment]
To provide an update, I found some issues with the Gfycat download function. I put in a temporary fix (b83593d575abc0db3c96d667bef4354db70b55f7). The fix works for 70% or so of Gfys (complete guess on the actual number). 

For the future, I plan on integrating [Py-Gfycat](https://github.com/ankeshanand/py-gfycat/) so that the actual files to download can be reliably retrieved. I'll leave this issue open until I do so.

**Comment by makuto** [comment]
Added support as of 213c9a10a3826e485b7229c979058f900cb3a587 (but you'll want latest to get subsequent fixes as well)
